### PR TITLE
FreeBSD Compatibility, find SDL2, libpng, libjpeg via CMake

### LINKED ISSUE #8: Compilation under Linux should use pkg-config
Compilation under Linux should ideally use [pkg-config](http://www.freedesktop.org/wiki/Software/pkg-config/) to find include directories and compiler options.
CMake 2.6 provides a script with a function, [pkg_search_module](http://www.cmake.org/cmake/help/cmake2.6docs.html#module:FindPkgConfig), to interface easily with pkg-config.

For instance, I'm under fedora and compilation fails, simply because in fedora, they bundled SDL2 and SDL2main in one archive file, thus only "-lSDL2" should be passed to the compiler and passing "-lsdl2main" provokes an error.  Besides they use capital letters.

    % pkg-config sdl2 --libs
    -lSDL2 -lpthread 

I'm investigating on how to fix it.

### PR DESCRIPTION
**Pull request by tony**
- Suppress switch errors with ``-Wswitch`` (clang 3.7)
- Find libpng and libjpeg via CMake
- Find SDL2 through CMake modules, this should also fix #8, eliminating the step to copy SDL libraries manually
- Switch shebangs on all scripts to ``/usr/bin/env sh`` to work in cases where ``BASH(1)`` is elsewhere or not present.
- chmod all scripts as executable 755 +x
- Tested on FreeBSD 11-CURRENT

freebsd-current

### CODE REVIEW

**Comment by frankinshtein** [comment]
1. I suppose you broken compatibility with Windows. Where you could download oxygine  any build any examples out of box
2. I refactored cmakelists.txt, but not yet commited it to gitbub
https://bitbucket.org/oxygine/oxygine-framework/src/b2952af213d10e08d4d65f11b191a1caccfcee78/CMakeLists.txt?at=dev&fileviewer=file-view-default

**Comment by tony** [comment]
Привет @frankinshtein, nice to meet you.

Windows is an important platform to distribute to indeed.

1. The switch to using CMake's module greatly enhance coverage on POSIX-like platforms.

 I do not have a Windows machine to test on, so wouldn't know.  Can you expand upon which part specifically would be broke?  Is it the libpng/libjpeg parts?

2. That's excellent.  Do you want me to rebase my CMakeLists.txt changes off your refactoring?

What version of Windows are you testing on? What version of CMake?

**Comment by frankinshtein** [comment]
привет)
1. agree. Yes, I mean libjpg,png and maybe SDL
2. I will commit big update soon and let you know

I'm using windows 10, old CMake

**Comment by tony** [comment]
@frankinshtein Okay. Commit your refactor first.  I'll prep a Windows environment in the mean time.

**Comment by frankinshtein** [comment]
done
https://github.com/oxygine/oxygine-framework/tree/dev

(it has not only cmake changes)

**Comment by frankinshtein** [comment]
I merged myself but reverted cmake changes

**Comment by tony** [comment]
@frankinshtein Thank you,

Where does that put the dev branch? That is your new refactor?

Is there any reason libpng, libjpeg and others?  Do any of the libraries require oxygine-specific patches?

Other than Windows support, did the CMake alterations pose any problem?

**Comment by frankinshtein** [comment]
>Where does that put the dev branch? That is your new refactor, correct?

dev branch is development branch of oxygine. It has all new code.

> Is there any reason libpng, libjpeg and others? Do any of the libraries require oxygine-specific patches?

don't understand question

> Other than Windows support, did the CMake alterations pose any other problem?

Current CMake version works fine with MinGW (codeblocks, clion etc), Ubuntu, VisualStudio 2010+.

**Pull request merged**
